name: squishilicious
favicon: null
layout_spectrum: 0.94974
typography_spectrum: 0.02360112965106964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b1819'
    - '#67c8e6'
    - '#dc438c'
    - '#827f80'
  brandStrength: 0.2680542969610542
  lightness: 0.10519437096081674
  saturation: 0.28638420021161437
  rhythmicContrast: 0.9953957297839224
purpose: []
