name: squishilicious
favicon: null
layout_spectrum: 0.94974
typography_spectrum: 0.02360112965106964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#90f4e3'
    - '#b8f4e7'
    - '#b3fbea'
    - '#cbf9f1'
    - '#c3fae0'
  brandStrength: 0.1875
  lightness: 0.10519437096081674
  saturation: 0.28638420021161437
  rhythmicContrast: 0.9953957297839224
purpose: []
